---
- name: basic configuration with launch template
  amazon.aws.autoscaling_group:
    name: webserver-asg
    region: "{{ aws_region }}"
    load_balancers: [ alb.name ]
    availability_zones: [ "{{ priv_az_01 }}", "{{ priv_az_02 }}" ]
    health_check_period: 60
    launch_template:
        version: '1'
        launch_template_name: webserver-launch-template
    default_cooldown: 90
    min_size: 1
    max_size: 4
    desired_capacity: 2
    vpc_zone_identifier: [ 'priv_sub_01', 'priv_sub_02' ]
    tags:
      - env: prod
        propagate_at_launch: true