---
- name: basic configuration with launch template
  amazon.aws.autoscaling_group:
    name: webserver-asg
    region: "{{ aws_region }}"
    target_group_arns: "{{ alb_tag_grp.target_group_arn }}"
    availability_zones: [ "{{ priv_az_01 }}", "{{ priv_az_02 }}" ]
    health_check_period: 60
    health_check_type: EC2
    launch_template:
        version: '1'
        launch_template_name: webserver-launch-template
    default_cooldown: 90
    min_size: 1
    max_size: 4
    desired_capacity: 2
    replace_all_instances: true
    vpc_zone_identifier: [ "{{ priv_sub_01_use1a.subnet.id }}", "{{ priv_sub_02_use1b.subnet.id }}" ]
    tags:
      - env: prod
      - Name: webserver
        propagate_at_launch: true