---
- name: playbook to host a simple HTML page on apache webserver
  hosts: all
  become: true # Perform all the Ansible playbook tasks as another user.
  become_user: root # Default username to be used by Ansible
  vars_files: # Contains all my secrets
    - vars/main.yml
  roles:
    - { role: geerlingguy.mysql }

  tasks:
    - name: Update "apt" repository
      apt:
        update_cache: yes # Run the equivalent of apt update
        autoclean: yes # Remove useless packages from the cache
        autoremove: yes

    - name: Install (git, apache2 unzip, curl, ufw)
      apt:
        pkg:
        - git
        - apache2
        - unzip
        - curl

# Create project directory and clone repository
    - name: Change the working directory to /var/www/ and create exam directory
      command: mkdir exam
      args:
        chdir: /var/www/
        creates: exam
    
    - name: Clone the project repo into a new directory
      git:
        repo: https://github.com/f1amy/laravel-realworld-example-app.git
        dest: /var/www/exam/laravel
        clone: yes
        update: no

    - name: Create the web.php file in the routes directory
      ansible.builtin.copy:
        dest: /var/www/exam/laravel/routes/web.php
        content: |
          <?php

          Route::get('/', function () {
              return view('welcome');
          });

# My custom script to modify the .env file
    - name: Create and edit the .env file
      ansible.builtin.copy:
        src: /var/www/exam/laravel/.env.example 
        dest: /var/www/exam/laravel/.env
        remote_src: yes

    - name: My script to modify .env
      ansible.builtin.script: /home/vagrant/mod_env.sh
      args:
        chdir: /home/admin
    
# Create Virtual Host File
    - name: Create an apache virtual host configuration file
      ansible.builtin.copy:
        dest: /etc/apache2/sites-available/exam.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin admin@philemonnwanne.me
              ServerName philemonnwanne.me
              ServerAlias www.philemonnwanne.me
              DocumentRoot /var/www/exam/laravel/public
    
              <Directory /var/www/exam/laravel/public>
                  AllowOverride All
              </Directory>
    
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

# Disable default apache page and enable laravel page
    - name: Enable a2enmod rewrite
      ansible.builtin.command: a2enmod rewrite

    - name: Disable default apache page and enable laravel page
      ansible.builtin.command: a2dissite 000-default.conf

    - name: Enable laravel page
      ansible.builtin.command: a2ensite exam.conf

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www/exam/laravel
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '775'

    - name: Restart apache web server
      ansible.builtin.command: systemctl restart apache2

    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Script to install PostgreSQL
      ansible.builtin.script: /home/vagrant/postgres.sh
      args:
        chdir: /home/admin



