# this playbook deploys the whole application stack in this site
---
- name: configure and deploy the webservers and application code
  hosts: localhost
  connection: local
  # become: true # perform all ansible playbook tasks as another user
  # become_user: root # default username to be used by Ansible
  roles:
    - aws
    # - nginx
    # - passenger
    # - python
    # - uwsgix
    # - common
