# tasks for /roles/aws/tasks/vpc
- name: create a vpc on aws
  import_tasks: vpc.yml

- name: create subnets in vpc
  import_tasks: subnet.yml

- name: create an internet gateway
  import_tasks: igw.yml

# - name: create a vpc on aws
#   import_tasks: endpoint.yml
