- name: create security group for bastion instance
  amazon.aws.ec2_security_group:
    name: bastion-sgrp
    description: allow ssh, http and https traffic
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow instances in the private subnet to reach out to the internet for security patches
  register: bastion_sgrp
