---
- name: script to install static page
  ansible.builtin.script: /home/vagrant/ansible/roles/httpd/files/init-script.sh
  args:
    chdir: /home/ec2-user

- name: set timezone to Africa/Lagos
  timezone:
    name: Africa/Lagos