---
- name: create an ALB and attach a listener
  amazon.aws.elb_application_lb:
    name: portfolio-elb
    security_groups:
      - "{{ elb_sgrp }}"
    subnets:
      - "{{ pub_az_01_use1a.subnet.id }}"
      - "{{ pub_az_02_use1b.subnet.id }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        SslPolicy: ELBSecurityPolicy-2015-05
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ elb_tag_grp.target_group_name }}"
    state: present
