- name: create the load balancer target group with instance targets
  community.aws.elb_target_group:
    name: alb-target-group
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    # health_check_protocol: http
    # health_check_path: /
    # successful_response_codes: "200,250-260"
    targets:
      - Id: "{{ webserver_01.instances[0].instance_id }}"
        Port: 80
      - Id: "{{ webserver_02.instances[0].instance_id }}"
        Port: 80
    state: present
    wait_timeout: 200
    wait: true
  register: alb_tag_grp

