- name: create security group for portfolio vpc
  amazon.aws.ec2_security_group:
    name: "{{ security_grp_name }}"
    description: allow http
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80
