- name: create a subnet for first az
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    az: "{{ az1 }}"
    cidr: "{{ az1_cidr }}"
    tags:
      Name: "{{ subnet_name }}"
  register: az1_use1a

- name: create a subnet for second az
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    az: "{{ az2 }}"
    cidr: "{{ az2_cidr }}"
    tags:
      Name: "{{ subnet_name }}"
  register: az2_use1b

