---
- name: Update the repository cache and install the latest version of package "nginx"
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: ensure the nginx service is running
  ansible.builtin.service:
    name: nginx
    state: started

- name: create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ document_root }}"
    state: directory
    mode: "0755"

- name: copy new html file
  ansible.builtin.copy:
    src: files/index.html
    dest: "{{ document_root }}"
    mode: "0644"

- name: create an nginx configuration file
  ansible.builtin.template:
    src: philemonnwanne.me.j2
    dest: "{{ nginx_conf_file }}"

- name: check for existence of symbolic link of the default nginx site
  ansible.builtin.stat:
    path: "{{ link_path }}"
  register: link

- name: disable the default nginx site
  file:
    path: "{{ link_path }}"
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: enable the new nginx site
  ansible.builtin.file:
    src: "{{ nginx_conf_file }}"
    dest: "{{ symlink_dest }}"
    state: link
  notify: restart the nginx service
