#!/usr/bin/bash

# UPDATE PACKAGE INDEX
sudo apt update && 
sudo apt install -y iputils-ping &&
sudo apt install -y nano &&
sudo apt install -y net-tools &&
# sudo apt install -y iproute2 &&
# sudo apt install -y ufw
# sudo apt install -y software-properties-common &&
# sudo add-apt-repository --yes --update ppa:ansible/ansible &&
# sudo apt install -y ansible