#!/bin/bash

# Create the file repository configuration:
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

# Import the repository signing key:
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# Update the package lists:
sudo apt-get update

# Install the l.
# This will install the latest version of PostgreSQL package along with a -contrib package that adds some additional utilities and functionality:
sudo apt-get -y install expect postgresql postgresql-contrib

# Ensure that the sPostgreSQL daemon is started
sudo systemctl start postgresql.service

# Login as the default postgres user
sudo -i -u postgres

# Create a new role (user) for postgres called 
sudo -u postgres createuser --philemonnwanne


expect \"Enter name of role to add:\"
send \"$MYSQL_USER_NAME\r\"

Enter name of role to add:
expect \"Shall the new role be a superuser?\ (y/n)\"
send \"y\r\"


expect \"Remove anonymous users?\"
send \"y\r\"

expect \"Disallow root login remotely?\"
send \"y\r\"