---
- name: create the webserver security group
  amazon.aws.ec2_security_group:
    name: webserver-sgrp
    description: allow http and https traffic
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow the webserver access to the internet for security patches etc
  register: webserver_sgrp
